"""Generate ``app/recruit/bank_data.py`` from the reviewed draft.

    python scripts/publish_recruit_bank.py

Publishes the Grant start-order slice only: non-STRIKE MOT / JOB / CMT
variants (C2). Does not emit C1 / C3 / C4 / C5.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from app.recruit.draft import C2_GROUPS, fd_name_hits, parse_issuable_c2

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "app" / "recruit" / "bank_data.py"

HEADER = '''\
# ruff: noqa: E501
"""Published C2-only Recruit bank (MOT / JOB / CMT, non-STRIKE).

Generated by ``scripts/publish_recruit_bank.py`` from
``recruit_question_bank_draft.md``. Do not edit by hand — re-run the script.
"""

from typing import TypedDict


class PublishedItem(TypedDict):
    scenario_id: str
    question_text: str
    family: str
    criterion_id: str


PUBLISHED_ITEMS: tuple[PublishedItem, ...] = (
'''


def main() -> int:
    items = parse_issuable_c2()
    by_group: dict[str, int] = {}
    for item in items:
        group = item.family.split("-", 1)[0]
        by_group[group] = by_group.get(group, 0) + 1
        if item.criterion_id != "c2":
            sys.exit(f"{item.scenario_id} is not c2")
        if item.family.split("-", 1)[0] not in C2_GROUPS:
            sys.exit(f"{item.scenario_id} is outside the C2 groups")
        hits = fd_name_hits(item.question_text)
        if hits:
            sys.exit(f"{item.scenario_id} names a department: {hits}")
        for forbidden in ("Listening for", "Sources:", "Pass 1", "Pass 2"):
            if forbidden in item.question_text:
                sys.exit(f"{item.scenario_id} leaked review prose: {forbidden}")

    expected = {"MOT": 40, "JOB": 26, "CMT": 15}
    if by_group != expected or len(items) != 81:
        sys.exit(f"expected MOT 40 + JOB 26 + CMT 15 = 81; got {by_group} ({len(items)})")

    lines = [HEADER]
    for item in items:
        lines.append("    {\n")
        lines.append(f"        \"scenario_id\": {json.dumps(item.scenario_id)},\n")
        lines.append(f"        \"question_text\": {json.dumps(item.question_text)},\n")
        lines.append(f"        \"family\": {json.dumps(item.family)},\n")
        lines.append(f"        \"criterion_id\": {json.dumps(item.criterion_id)},\n")
        lines.append("    },\n")
    lines.append(")\n")
    OUT.write_text("".join(lines))
    print(f"wrote {len(items)} items to {OUT.relative_to(ROOT)} ({by_group})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
