"""Generate ``app/recruit/bank_data.py`` from the reviewed draft.

    python scripts/publish_recruit_bank.py

Publishes every non-STRIKE family (START ORDER 2026-09-11). C2-only ~81
was the prior live bank.
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

from app.recruit.draft import ALL_GROUPS, fd_name_hits, parse_issuable
from app.recruit.families import GROUP_CRITERION, criterion_for_family

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "app" / "recruit" / "bank_data.py"

HEADER = '''\
# ruff: noqa: E501
"""Published Recruit bank (all reviewed non-STRIKE families).

Generated by ``scripts/publish_recruit_bank.py`` from
``recruit_question_bank_draft.md``. Do not edit by hand — re-run the script.
"""

from typing import TypedDict


class PublishedItem(TypedDict):
    scenario_id: str
    question_text: str
    family: str
    criterion_id: str


PUBLISHED_ITEMS: tuple[PublishedItem, ...] = (
'''


def main() -> int:
    items = parse_issuable()
    by_group: Counter[str] = Counter()
    by_criterion: Counter[str] = Counter()
    for item in items:
        group = item.family.split("-", 1)[0]
        by_group[group] += 1
        by_criterion[item.criterion_id] += 1
        if group not in ALL_GROUPS:
            sys.exit(f"{item.scenario_id} is outside the published groups")
        if item.criterion_id != criterion_for_family(item.family):
            sys.exit(
                f"{item.scenario_id} criterion {item.criterion_id} "
                f"!= {criterion_for_family(item.family)}"
            )
        if item.criterion_id != GROUP_CRITERION[group]:
            sys.exit(f"{item.scenario_id} criterion mismatch for {group}")
        hits = fd_name_hits(item.question_text)
        if hits:
            sys.exit(f"{item.scenario_id} names a department: {hits}")
        for forbidden in ("Listening for", "Sources:", "Pass 1", "Pass 2"):
            if forbidden in item.question_text:
                sys.exit(f"{item.scenario_id} leaked review prose: {forbidden}")

    if not items:
        sys.exit("published bank is empty")
    if by_criterion.keys() <= {"c2"}:
        sys.exit(f"bank is C2-only; non-C2 publish is required: {dict(by_criterion)}")

    lines = [HEADER]
    for item in items:
        lines.append("    {\n")
        lines.append(f"        \"scenario_id\": {json.dumps(item.scenario_id)},\n")
        lines.append(f"        \"question_text\": {json.dumps(item.question_text)},\n")
        lines.append(f"        \"family\": {json.dumps(item.family)},\n")
        lines.append(f"        \"criterion_id\": {json.dumps(item.criterion_id)},\n")
        lines.append("    },\n")
    lines.append(")\n")
    OUT.write_text("".join(lines))
    print(
        f"wrote {len(items)} items to {OUT.relative_to(ROOT)} "
        f"(groups={dict(by_group)} criteria={dict(by_criterion)})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
