"""Generate the blind scoring exercise for the SME.

    python scripts/recruit_review_exercise.py

Writes `reviews/c3-scoring-exercise.md`: ten answers and a block to score them in, with
nothing about what any of them is testing and nothing about what the rubric says. Both
omissions are the point. A reviewer told that an answer probes the level 4 boundary knows
where to land, and a reviewer shown the anchors is checking his reading of the rubric
rather than supplying the judgment the rubric is supposed to encode.

The file is version-controlled and becomes the review record — `recruit_design_decisions.md`
requires that SME review leave diffs, history, and a record of who approved what, and a
score typed into a chat window leaves none of those.

Score it, then run `scripts/recruit_review_compare.py` to see where you and the anchors
disagree.
"""

import re
from pathlib import Path

from app.critique.review_set import ANSWERS, QUESTION

OUT = Path("reviews/c3-scoring-exercise.md")

HEADER = f"""# Criterion 3 — scoring exercise

*Blind review of `recruit_rubric_c3_teamwork.md`. Generated by
`scripts/recruit_review_exercise.py`; do not hand-edit the answers, only the scores.*

## What this is for

The anchors in Criterion 3 were drafted by Claude. The dimension, its two axes and the
behavioural framing come from published department sources, but **every discrimination
between adjacent scores is inference**, and that is the part no public source supplies and
no measurement settles. This exercise supplies it.

Score each answer **from your own judgment, without opening the rubric.** Where your score
and the anchors agree, that clause needs no further attention. Where they disagree, that is
the clause to rewrite, and the disagreement says what is wrong with it. Ten answers rather
than fifteen clauses, and it converges on the few that are actually wrong.

Do not read the rubric first. If you have just been working in it, leave this an hour.

## The question each candidate was asked

> {QUESTION}

## How to score

Write one value per answer in the block at the bottom. Anything you can defend is a valid
answer, including refusing to score one.

| Value | Means |
|---|---|
| `1`–`5` | The anchor it lands on. Use `4A` or `4B` if you want to record the route, or just `4`. |
| `not assessable` | His history genuinely does not contain what this criterion asks about. |
| `not answered` | He gave nothing to judge either way — not the same thing. |
| `?` | You could not decide. A real answer and worth recording. |

An answer you cannot place is usually a rubric problem rather than a you problem, so `?`
is signal, not a gap.

A note after the score is optional and worth more than the score. *Why* an answer sits
where it does is what rewrites an anchor; the number alone only says something is wrong.

---
"""

FOOTER = """---

## Your scores

Fill in after the `=`. Free text after the score is kept as your note.

```scores
{lines}
```

---

*When this is filled in: `python scripts/recruit_review_compare.py`*
"""


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)

    body = [HEADER]
    for answer in ANSWERS:
        body.append(f"\n## {answer.ref}\n\n")
        body.append("\n".join(f"> {line}" for line in answer.transcript.strip().splitlines()))
        body.append("\n")

    lines = "\n".join(f"{answer.ref} = " for answer in ANSWERS)
    body.append("\n" + FOOTER.format(lines=lines))

    text = "".join(body)

    # The exercise must not leak what each answer probes, or the judgment stops being
    # independent and the instrument measures nothing. Checked against the clause-ID
    # pattern rather than bare words — an earlier version matched the "note" in "a note
    # after the score" and refused to write a perfectly clean file.
    for answer in ANSWERS:
        assert answer.probes not in text, f"{answer.ref} leaked its probe into the exercise"
    leaked = re.findall(r"\bc3\.(?:anchor|note)\.\w+", text)
    assert not leaked, f"exercise leaks clause IDs: {sorted(set(leaked))}"

    OUT.write_text(text)
    print(f"wrote {OUT} — {len(ANSWERS)} answers, {len(text)} chars")
    print("score it without opening the rubric, then run scripts/recruit_review_compare.py")


if __name__ == "__main__":
    main()
